### ISSUE TITLE
Uninitialized Constant

### ISSUE THREAD

**Issue by ryangurn** [fhur/phisher#1]
testing.rb:1:in `<main>': uninitialized constant Phisher (NameError)

Here is the code that I was using.

phisher = Phisher.new
phisher.verify("google.com")

Please advise how to fix this error.

**Comment by fhur** [comment]
Hi @ryangurn, this project is still in early development. You will need to require the Phisher class located at https://github.com/fhur/phisher/blob/master/lib/phisher/phisher.rb

**Comment by ryangurn** [comment]
That does not happen when you install it as a gem?

**Comment by fhur** [comment]
`gem install phisher` + `require 'phisher'` is equivalent to including this file(https://github.com/fhur/phisher/blob/master/lib/phisher.rb) which is currently empty.
